### ISSUE TITLE
Feature Request: Add Multiple ChatGPT Instances/Accounts/API

### ISSUE THREAD

**Issue by austinsonger** [bentleymi/ChatGPT-4-Splunk#28]
Use Case:

We allow multiple employees use ChatGPT at work, but they must use their work email account for their account.

It would be nice to add all of the users API information to Splunk so it would be easy to monitor what they are inputting to ensure PII or PHI information isn't being entering into OpenAPI Cloud Infrastructure.

**Comment by bentleymi** [comment]
I added the ability to specify a default key and org as well as ability to add non-defaults and specify them using the command.

`| openai org="test" key="test"  `

Would query passwords.conf for:
api_key_test and org_id_test

And `| openai`

Would query passwords.conf for:
api_key_default and api_key_default

This change in the behavior of passwords.conf requires specific upgrade instructions if you dont want to re-add the org and key through the new setup page.   Please see the readme.md for more details.
