### ISSUE TITLE
No such organization or key

### ISSUE THREAD

**Issue by CXW-Sarah-Kladstrup** [bentleymi/ChatGPT-4-Splunk#31]
**Name of the app**
ChatGPT 4 Splunk

**Describe the bug**
After having added the organization name and value and the API key and value, I am unable to perform a search using the openai command successfully.

**To Reproduce**
1. Install the plugin on Splunk.
2. In the "setup" page for the plugin

- enter the Organization Name in the "Enter Organization Name" field.
```ConductixWampfler```
- enter the Organization Value in the "Enter Organization Value" field.
```org-blahblahblah```
- enter the API Key Name in the "Enter API Key Name" field.
```CXW-Splunk```
- enter the API Key Value in the "Enter API Key Value" field.
```sk-blahbalahasdlfkjasdf```

3. Click on "Complete Setup"
4. From the "New Search" page/tab, add the following:
```host=namehere source!="Perfmon*"  NOT "JIRA-STATS" sourcetype!="atlassian-jira-gc" | openai prompt="Given these logs, why did Jira stop responding?" model="gpt-3.5-turbo"```
5. Limit the search to 15 minutes or some other small window.
6. Click on the magnifying glass icon.
7. Receive the following error (verbatim):
```command="openai", No such organization: org-ABCDEFG12345.```

**Expected behavior**
I would expect:
1. the error display my accurate org key
2. To return results from OpenAI.

**Screenshots**
![image](https://github.com/bentleymi/ChatGPT-4-Splunk/assets/140117787/ed481b46-e242-4249-9cad-5714f054b53b)

**Splunk SOAR Version (please complete the following information):**
 -  Unprivileged Install?
 - running on a VM using Windows Server 2019 Datacenter, version 1809, OS build 17763.3770
 - App Version:  Splunk Enterprise 9.0.5 Build: e9494146ae5c

**Comment by bentleymi** [comment]
Which version of the app?

In latest versions there exists 2 behaviors.

1. Specifying an org:

 | openai org={ORG} ...
 
 Where {ORG} = the name you gave your org on the setup page

2. Using the default org:

| openai  ...

  Where {ORG} defaults to "default" and so the setup page has instructions to create a default .

**Comment by bentleymi** [comment]
Given your example above you would need to use this command

| openai org=ConductixWampfler

If you prefer "ConductixWampfler" to be the default then go through setup as follows:

enter the Organization Name in the "Enter Organization Name" field.
`default`
enter the Organization Value in the "Enter Organization Value" field.
`org-blahblahblah`
enter the API Key Name in the "Enter API Key Name" field.
`default`
enter the API Key Value in the "Enter API Key Value" field.
`sk-blahbalahasdlfkjasdf`

**Comment by CXW-Sarah-Kladstrup** [comment]
![image](https://github.com/bentleymi/ChatGPT-4-Splunk/assets/140117787/956e8f3d-68fd-471b-bc7c-9d7c9c032c49) Is this expected behaviour?

**Comment by bentleymi** [comment]
yes, but you're not using the syntax correctly.

**Comment by bentleymi** [comment]
Please re-do your setup as follows:

enter the Organization Name in the "Enter Organization Name" field.
`default`     <- do not change this from default
enter the Organization Value in the "Enter Organization Value" field.
`org-blahblahblah`  <- change this to your org
enter the API Key Name in the "Enter API Key Name" field.
`default`   <- do not change this from default
enter the API Key Value in the "Enter API Key Value" field.
`sk-blahbalahasdlfkjasdf`  <- change this to your key for your org

Save the settings


Run | openai

**Comment by bentleymi** [comment]
Like this:
![image](https://github.com/bentleymi/ChatGPT-4-Splunk/assets/4107863/8465a30b-eb4e-4085-a774-f19e72e7e720)

**Comment by bentleymi** [comment]
Like this:
![image](https://github.com/bentleymi/ChatGPT-4-Splunk/assets/4107863/e854887f-6bba-4720-91dd-17904ab2272e)

**Comment by CXW-Sarah-Kladstrup** [comment]
Unfortunately, that is giving me the same result:
![image](https://github.com/bentleymi/ChatGPT-4-Splunk/assets/140117787/a2c3d8f1-b734-4676-b611-24425a5e8349)

Also, OpenAI API Version: 3.2.0 Build: 4

**Comment by bentleymi** [comment]
Please share a copy of your passwords.conf without the hashed password = lines.

Did you upgrade from a previous version?

**Comment by CXW-Sarah-Kladstrup** [comment]
![image](https://github.com/bentleymi/ChatGPT-4-Splunk/assets/140117787/3e7682a3-544b-4770-a7c8-31b8ffe0ba85)

No, we did not upgrade.

**Comment by bentleymi** [comment]
That looks like it should.  Can you try removing all the contents, and then going through setup again and to create a "default" org and api key?  Then test one more time for me with just  | openai?

**Comment by bentleymi** [comment]
I just did a fresh install and confirmed. The only way you get org-ABCDEFG12345 is if you do not put in a value for your organization and instead use the placeholder text.

![image](https://github.com/bentleymi/ChatGPT-4-Splunk/assets/4107863/7a7a023c-84b4-4c08-bf5f-6722d497c727)

So to fix this, remove passwords.conf and re-enter the correct details on the setup page.

Tested from fresh install with Splunk 8.0.5 and ChatGPT-4-Splunk v3.2.0

**Comment by CXW-Sarah-Kladstrup** [comment]
I will try that! :D

Thanks,
Sarah Edwards Kladstrup
Dev Ops and QA Automation
***@***.******@***.***>

Conductix-Wampfler (Conductix, Inc.)
10102 F Street, Omaha, NE 68127 (USA)  www.conductix.us<http://www.conductix.us/>
Phone: (800) 521-4888   (402) 339-9300, Ext. 9312   Fax: (800) 780-8329   (402) 339-9627
***@***.******@***.***%3e>

**Comment by CXW-Sarah-Kladstrup** [comment]
Well, I'm now getting, "command="openai", You exceeded your current quota, please check your plan and billing details." so I would say that fixed it! Thank you.
